### ISSUE TITLE
Migration 文件生成包

### ISSUE THREAD

**Issue by yanwenwu** [top-think/think-awesome#7]
## 目的
如果你还未使用或者正想使用数据库迁移功能，但又不并不想自己写迁移文件的话，这个工具可以很好的帮助实现文件迁移 目前提供了 Laravel5.5+ 和 Thinkphp6+ 的迁移文件的生成。

## 如何使用
> composer require jaguarjack/migration-generator 1.0

> php think migration:generate

[migration-generator](https://github.com/yanwenwu/migration-generator)

**Comment by liu21st** [comment]
已经收录
