### ISSUE TITLE
【开源自荐】laket-admin 是使用 Thinkphp 和 Layui 开发的后台管理系统

### ISSUE THREAD

**Issue by deatil** [top-think/think-awesome#71]
##  项目地址
https://github.com/deatil/laket-admin

## 项目介绍
*  `laket-admin` 是基于 `Thinkphp` 的PHP通用后台管理系统，升级 Thinkphp 到 v8 版本
*  使用 `layui` 搭建后台管理界面
*  基于 Service 服务提供者的插件系统，让系统扩展更方便

**Comment by liu21st** [comment]
本库不再更新 请提交至官网应用中心 https://www.thinkphp.cn/app 或者扩展中心 https://www.thinkphp.cn/ext
